name: inscore_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.1.0

  # State Management
  provider: ^6.0.5

  # Routing
  go_router: ^14.2.0

  # HTTP & API
  http: ^1.2.1
  dio: ^5.4.0

  # Local Storage
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0

  # Utilities
  equatable: ^2.0.5
  intl: ^0.20.2
  flutter_dotenv: ^6.0.0
  connectivity_plus: ^7.0.0
  logger: ^2.0.2
  image_picker: ^1.0.7
  fl_chart: ^0.69.0
  url_launcher: ^6.2.5

  # Code Generation
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # Code Generation
  build_runner: ^2.4.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1

  # Launcher Icons
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo/

# Launcher Icons Configuration
flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo/Logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/logo/Logo.png"
    background_color: "#2F80ED"
  windows:
    generate: true
    image_path: "assets/images/logo/Logo.png"
    icon_size: 48 # min:48, max:256, default: 48
